### ISSUE TITLE
[FEATURE] [MODDED] Rain triggers jogging in addition to fog

### ISSUE THREAD

**Issue by VoyagerSoa** [VoyagerSoa/jad_candlelightMoonfall#6]
Rain and fog will trigger zombie jogging. This will need a fork of existing mods to include fog functionality, as well as rewarding extra combat XP in these instances.

**Comment by Kyaace** [comment]
I'm working this issue, should have something to test by Monday

**Comment by Kyaace** [comment]
Submitted my patches to Nights printers and Rewarding Night Combat. Needs more comprehensive testing but seems to work in SP

**Comment by VoyagerSoa** [comment]
Functionality is unlikely to not work in multiplayer. Will close the issue now as completed.
